---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - ansible.builtin.include_tasks: java-11.yml

  roles:
    - role: shaneholloman.java
      when: ansible_os_family == 'Debian'
    - role: shaneholloman.puppet
