- name: Update package cache
  ansible.builtin.command:
    cmd: "{{ ansible_pkg_mgr }} update"
  when: ansible_os_family in ['Debian', 'RedHat']

- name: Set the java_packages variable (Debian)
  ansible.builtin.set_fact:
    java_packages:
      - openjdk-11-jdk
  when: ansible_os_family == 'Debian'

- name: Set the java_packages variable (RedHat)
  ansible.builtin.set_fact:
    java_packages:
      - java-11-openjdk-devel
  when: ansible_os_family == 'RedHat'

- name: Install Java packages
  ansible.builtin.package:
    name: "{{ java_packages }}"
    state: present
